server.port=8080

softwaredevelopmentbooks.applciation.path=/api
softwaredevelopmentbooks.controller.path=${softwaredevelopmentbooks.applciation.path}/softwaredevelopmentbooks
softwaredevelopmentbooks.endpoints.getbooks=/getBooks