server.port=8080

softwaredevelopmentbooks.application.path=/api
softwaredevelopmentbooks.controller.path=${softwaredevelopmentbooks.application.path}/softwaredevelopmentbooks
softwaredevelopmentbooks.endpoints.getbooks=/getBooks
softwaredevelopmentbooks.endpoints.getpricingsummary=/getPricingSummary